Completed Javascript Functions.
randygerada/prep-0922-code-solutions pull request #13
Opened 2022-09-28 21:37 UTC by randygerada

<img width="797" alt="Screen Shot 2022-09-28 at 2 17 21 PM" src="https://user-images.githubusercontent.com/113477527/192893123-ac49698d-3edb-4c82-96af-72c1af72011a.png">

2022-09-28 23:01 UTC, thebearingedge requested changes

2022-09-28 23:01 UTC, thebearingedge commented on prep-javascript-functions/main.js
> +  var total4 = ((number) ^ 3);
`^` is actually a special operator for XOR (exclusive OR). But you can multiply `number * number * number`

2022-09-28 23:25 UTC, randygerada commented
<img width="745" alt="Screen Shot 2022-09-28 at 4 24 41 PM" src="https://user-images.githubusercontent.com/113477527/192905693-63c6216d-d6dd-406b-8a04-be3852106e09.png">

2022-09-29 00:44 UTC, thebearingedge approved these changes

2022-09-29 20:29 UTC, merged